/**
 * A biome tag -> number (Same values for biome checker)
 */
export const BIOME_MAP = {
  "minecraft:ocean": 1,
  "minecraft:bamboo_jungle_hills": 2,
  "minecraft:basalt_deltas": 3,
  "minecraft:beach": 4,
  "minecraft:birch_forest": 5,
  "minecraft:birch_forest_hills": 6,
  "minecraft:birch_forest_hills_mutated": 7,
  "minecraft:birch_forest_mutated": 8,
  "minecraft:cherry_grove": 9,
  "minecraft:cold_beach": 10,
  "minecraft:cold_ocean": 11,
  "minecraft:cold_taiga": 12,
  "minecraft:cold_taiga_hills": 13,
  "minecraft:cold_taiga_mutated": 14,
  "minecraft:crimson_forest": 15,
  "minecraft:deep_cold_ocean": 16,
  "minecraft:deep_dark": 17,
  "minecraft:deep_frozen_ocean": 18,
  "minecraft:deep_lukewarm_ocean": 19,
  "minecraft:deep_ocean": 20,
  "minecraft:deep_warm_ocean": 21,
  "minecraft:desert": 22,
  "minecraft:desert_hills": 23,
  "minecraft:desert_mutated": 24,
  "minecraft:dripstone_caves": 25,
  "minecraft:extreme_hills": 26,
  "minecraft:extreme_hills_edge": 27,
  "minecraft:extreme_hills_mutated": 28,
  "minecraft:extreme_hills_plus_trees": 29,
  "minecraft:extreme_hills_plus_trees_mutated": 30,
  "minecraft:flower_forest": 31,
  "minecraft:forest": 32,
  "minecraft:forest_hills": 33,
  "minecraft:frozen_ocean": 34,
  "minecraft:frozen_peaks": 35,
  "minecraft:frozen_river": 36,
  "minecraft:grove": 37,
  "minecraft:hell": 38,
  "minecraft:ice_mountains": 39,
  "minecraft:ice_plains": 40,
  "minecraft:ice_plains_spikes": 41,
  "minecraft:jagged_peaks": 42,
  "minecraft:jungle": 43,
  "minecraft:jungle_edge": 44,
  "minecraft:jungle_edge_mutated": 45,
  "minecraft:jungle_hills": 46,
  "minecraft:jungle_mutated": 47,
  "minecraft:legacy_frozen_ocean": 48,
  "minecraft:lukewarm_ocean": 49,
  "minecraft:lush_caves": 50,
  "minecraft:mangrove_swamp": 51,
  "minecraft:meadow": 52,
  "minecraft:mega_taiga": 53,
  "minecraft:mega_taiga_hills": 54,
  "minecraft:mesa": 55,
  "minecraft:mesa_bryce": 56,
  "minecraft:mesa_plateau": 57,
  "minecraft:mesa_plateau_mutated": 58,
  "minecraft:mesa_plateau_stone": 59,
  "minecraft:mesa_plateau_stone_mutated": 60,
  "minecraft:mushroom_island": 61,
  "minecraft:mushroom_island_shore": 62,
  "minecraft:pale_garden": 64,
  "minecraft:plains": 65,
  "minecraft:redwood_taiga_hills_mutated": 66,
  "minecraft:redwood_taiga_mutated": 67,
  "minecraft:river": 68,
  "minecraft:roofed_forest": 69,
  "minecraft:roofed_forest_mutated": 70,
  "minecraft:savanna": 71,
  "minecraft:savanna_mutated": 72,
  "minecraft:savanna_plateau": 73,
  "minecraft:savanna_plateau_mutated": 74,
  "minecraft:snowy_slopes": 75,
  "minecraft:soulsand_valley": 76,
  "minecraft:stone_beach": 77,
  "minecraft:stony_peaks": 78,
  "minecraft:sunflower_plains": 79,
  "minecraft:swampland": 80,
  "minecraft:swampland_mutated": 81,
  "minecraft:taiga": 82,
  "minecraft:taiga_hills": 83,
  "minecraft:taiga_mutated": 84,
  "minecraft:the_end": 85,
  "minecraft:warm_ocean": 86,
  "minecraft:warped_forest": 87,
};

export const CANDLES = [
  "candle",
  "white_candle",
  "light_gray_candle",
  "gray_candle",
  "black_candle",
  "brown_candle",
  "red_candle",
  "orange_candle",
  "yellow_candle",
  "lime_candle",
  "green_candle",
  "cyan_candle",
  "light_blue_candle",
  "blue_candle",
  "purple_candle",
  "magenta_candle",
  "pink_candle",
];
export const UP = {
  x: 0,
  y: 1,
  z: 0,
};
export const DOWN = {
  x: 0,
  y: -1,
  z: 0,
};
export const NORTH = {
  x: 0,
  y: 0,
  z: 1,
};
export const SOUTH = {
  x: 0,
  y: 0,
  z: -1,
};
export const WEST = {
  x: 1,
  y: 0,
  z: 0,
};
export const EAST = {
  x: -1,
  y: 0,
  z: 0,
};
export enum Oxidization {
  Normal = 0,
  Exposed = 1,
  Weathered = 2,
  Oxidized = 3,
}
